//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MK_API_Proc.DB_Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Adress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp_Adress()
        {
            this.newEmps = new HashSet<newEmp>();
        }
    
        public int AdressId { get; set; }
        public string AdressCode { get; set; }
        public string Building { get; set; }
        public string ZipCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newEmp> newEmps { get; set; }
    }
}
