//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MK_API_Proc.DB_Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDept
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterDept()
        {
            this.newEmps = new HashSet<newEmp>();
        }
    
        public int DepMId { get; set; }
        public string DepCode { get; set; }
        public string DepName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newEmp> newEmps { get; set; }
    }
}
