//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MK_API_Proc.DB_Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class newEmp
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AdressId { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> DepMId { get; set; }
    
        public virtual Emp_Adress Emp_Adress { get; set; }
        public virtual MasterDept MasterDept { get; set; }
    }
}
